Changed math.h to cmath due to math.h causing errors.
* Today while testing the bot we encountered a
  error we have never seen before:

  "CXX src/main.cpp"
  In file included from src/main.cpp:10:
  In file included from include\vex.h:1:
  c:\Users\FRC1\AppData\Roaming\Code\User\globalStorage\vexrobotics.vexcode\sdk\cpp\V5\V5_20240802_15_00_00/vexv5/gcc/include\math.h:1:1: error: C++ requires a type specifier for all declarations
  RAMS((long double, long double));
  ^
  c:\Users\FRC1\AppData\Roaming\Code\User\globalStorage\vexrobotics.vexcode\sdk\cpp\V5\V5_20240802_15_00_00/vexv5/gcc/include\math.h:1:18: error: expected ')'
  RAMS((long double, long double));
                 ^

* Talking with Uche we were not able to figure out
  what modifications was cauing this error until
  we figured out it was a error in math.h in the
  vex SDK. When it is compiled with the C header,
  math.h appears to cause this error, and we
  are not sure why.